env:
language: node_js
node_js:
- node
notifications:
  email: false
services:
- mongodb
before_script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: lJXLnXThnjUKtGDEuhD/+iNjrKOUxLQf2bcBWJHl9vxUc2sEjQYw1pYKN0PrNVRdKQF3i6SjvAbYHoX20C/Z/1UEEmt98fc12n5aSeWWpCVsgzz/AvQQLhAxsOmJ4Z+w4SYVAOfkhGihEV7gM66eDkBhaHb+WKjbbqYRBHrJtJAajzuxqwhjo46LJnZ3KflTi9fnc87H0AHByjaw4ybZpLb+cbVpV9PMWWSBqXFggx3GNnFm+Tm69J8UsQMZsxolNsSeMWljF6AguHdMc/7BVJ9R2VZcOLhOR5sscEypiPDWo8Jlo6pMhBEQvyHRTFQ2Hs9j0j05kjMrzEOezc71oONzHUvt4KUzapDfVxdhsikxmMu0ONPctwOQMgQDygN1nq0wOHiFf4XY+eA6uR9h4DfKQkJTafTPxcby5x8yaOJX02eqMh86CkRICPj7TikK3g293gFNr2lBk3QLzI35IHaU3wOYLp+PRVEz23Zxcu8T2RTegjZru2f62R4FiUz5Jq9Dyhm9WxT6spGBL/B6i8JPXxLVkEPrgd5JGIRECko3QdB3yqrjlYfUvrXIRVFFH9gq0/sINE86pMX9Y+qArFbj9hBy6S7uNnf2IcglaOjPD1gEcxl4qgV4LhtA6x0ZcYzpLdosA1+MWQKsjS4/3wbTCnTQ8PtwjZDliN6mxC8=
  app: expense-tracker-dayo
  on:
    tags: true
    all_branches: true
